name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main] # Se déclenche quand tu pousses sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Important si tes fichiers .json de modèles sont lourds

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://NS78:$HF_TOKEN@huggingface.co/spaces/NS78/heart-disease-api main