name: Sync Backend to Hugging Face

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Au cas où les modèles soient déjà en LFS sur GitHub

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 1. On crée un dossier temporaire propre hors du dépôt Git actuel
          mkdir -p /tmp/hf_deploy
          cp -r backend/* /tmp/hf_deploy/
          
          cd /tmp/hf_deploy
          
          # 2. On crée le fichier de configuration LFS exigé par Hugging Face
          echo "*.joblib filter=lfs diff=lfs merge=lfs -text" > .gitattributes
          echo "*.json filter=lfs diff=lfs merge=lfs -text" >> .gitattributes
          
          # 3. NOUVEAU : On crée le README.md avec la configuration Docker
          cat <<EOF > README.md
          ---
          title: Heart Disease API
          emoji: 🫀
          colorFrom: red
          colorTo: pink
          sdk: docker
          app_port: 7860
          ---
          EOF
          
          # 4. On initialise un nouveau Git tout neuf sans l'historique bloquant
          git init
          git checkout -b main
          git add .
          git commit -m "Deploy API to Hugging Face"
          
          # 5. On force l'envoi sur ton Space
          git push --force https://NS78:${HF_TOKEN}@huggingface.co/spaces/NS78/heart-disease-api main